# Generated by Django 5.2.1 on 2025-05-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vendor/'),
        ),
    ]
