# Generated by Django 5.2.1 on 2025-05-12 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_service', '0002_alter_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='image',
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vendor_service.vendor')),
            ],
        ),
    ]
