# Generated by Django 5.2.1 on 2025-05-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_service', '0008_vendor_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='owner',
        ),
    ]
