# Generated by Django 5.2.1 on 2025-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0004_alter_service_category'),
        ('vendor_service', '0010_rename_name_vendor_business_name_vendor_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorimage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='images', to='catalog_service.servicecategory'),
        ),
    ]
