# Generated by Django 5.2.1 on 2025-05-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_service', '0011_vendor_location_vendorimage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
