# Generated by Django 5.2.1 on 2025-05-13 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0003_delete_product_service_vendor_service_category'),
        ('review_service', '0002_remove_review_product_review_service'),
        ('user_service', '0001_initial'),
        ('vendor_service', '0010_rename_name_vendor_business_name_vendor_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='user_service.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog_service.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendor_service.vendor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'service')},
        ),
    ]
