# Generated by Django 5.2.1 on 2025-05-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0006_alter_service_available_alter_service_description_and_more'),
        ('notification_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_to',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user_from',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='catalog_service.service'),
            preserve_default=False,
        ),
    ]
