# Generated by Django 5.2.1 on 2025-05-12 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0002_service_servicecategory'),
        ('interaction_service', '0002_remove_interaction_product_interaction_service'),
        ('review_service', '0002_remove_review_product_review_service'),
        ('vendor_service', '0010_rename_name_vendor_business_name_vendor_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vendor_service.vendor'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog_service.servicecategory'),
        ),
    ]
