# Generated by Django 5.2.1 on 2025-05-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0003_delete_product_service_vendor_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_services', to='catalog_service.servicecategory'),
        ),
    ]
