# Generated by Django 5.2.1 on 2025-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_service', '0004_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
